### ISSUE TITLE
about the data type

### ISSUE THREAD

**Issue by Yongquan-He** [lajus/amie#1]
Dear author. Sorry to bother you,I am a student,now I want do an experiment about kg,so I want to uses this project. But my experimental datatype is just txt. Each line in the file is head_entity relation tail_entity, so I don't know how to solve

**Comment by lajus** [comment]
Hello, 

Note in order to build this repo, you may need to first mvn install libs in the amie-utils repository.

I am assuming you want to use AMIE (this repo contains also other sub-projects).
Now, AMIE Main-Class being amie.mining.AMIE, you can either:
* mvn install this repo and use the executable jar in mining/target/
* directly do mvn exec:java -Dexec.mainClass="amie.mining.AMIE" -Dexec.arguments="-h" and put appropriate command line arguments in place of -h.

It will read any text file such that there is one triple per line. Given a separator, by default TAB, it will split each line with this separator. If it results in strictly more than 3 splits, it will ignore the first split. Thus it reads any triple in files formated as follows:
* [subject][SEP][predicate][SEP][object]\n
* [factid][SEP][subject][SEP][predicate][SEP][object][SEP...|\n]
where SEP is by default a tabulation and can be changed via the -d command line option. Make sure the separator does not appear in the entities or litterals as it does not handle escaping nor quoting as in the CSV standard.

Tell me if you need more informations,
Jonathan

**Comment by Yongquan-He** [comment]
Thanks for your reply！ It's very helpful for me. I really appreciate your help very much！

**Comment by Yongquan-He** [comment]
Sorry to bother you again，now I do an experiment about kg, recommend system based on rule and path. So I want to know that if I have a file,which was consisted of triples of my query result. Can I predict the missing relation by using some method in this project. I have not a good command of java, so I want to extract the missing relation and then process it with Python.

**Comment by lajus** [comment]
Hello, I am not sure of what you want to do. 

The AMIE class mine Horn rules that satisfy some quality measures as explained in [https://suchanek.name/work/publications/vldbj2015.pdf](url). There is also my work on mining obligatory attributes in incomplete KB in the typing module [https://suchanek.name/work/publications/www-2018.pdf](url).

This is the latest development version of the AMIE project [https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/amie/](url) since I forked it to "mavenize" everything, the late development track is in the amie-old repository.

You should maybe try the old released version of AMIE (in the project page above) first to see if it fits your needs.

Cheers,
Jonathan
