### ISSUE TITLE
AMIE+ evaluation code

### ISSUE THREAD

**Issue by falcaopetri** [lajus/amie#6]
Hi. I'm interested in the code used to evaluate AMIE+'s mined rules. 

The [#init](/lajus/amie/tree/init) branch seems to be a mavenized AMIE+ with a bug fix to QueryEquivalence, is that right? Which means that [init/rules/src/main/java/amie/rules/eval](https://github.com/lajus/amie/tree/init/rules/src/main/java/amie/rules/eval) should be the evaluation code?

Is there any example on how to use the eval classes? `RuleHitsEvaluator` seems to be the main interface to them.

----
Oh, and last but not least, thanks for setting up this repo and continuing to improving the algo.

**Comment by lajus** [comment]
Hi,

The init branch is not exactly the same AMIE+ than the jar file available on the MPI website. This is the continuation of Luis' developement branch which was on svn, but you can access [here](https://github.com/lajus/amie-old). 

If I remember well, the major changes in the dev version compared to the release was the Queue used by AMIE which has been made generational in order to solve an issue with duplicate elimination (that had false negative in the old version).

I am not accustomed to the classes in the package `amie.rules.eval` as it is Luis' code and I have not used it so far but for what I understand:
`RulesHitEvaluator`: takes as inputs 3 files: the rules, the training KB and the testing KB.
It can be useful when you have two versions of the same KB, one more complete than the other, for example yago2 and yago2s. Assuming that you "trained", here you mined the rules, on the training dataset (yago2), it computes the precision of the new predictions on the testing dataset (yago2s) under CWA.
There is also `PCAFalseFactsSampler` that takes a kb file, a number and a rule file as argument and outputs new pca predictions of the rules (that can then be manually checked to evaluate the precision of the PCA).

As for the rule file, it should work if you feed it the output of AMIE in a file (any tsv file (tab separated value) where the first column contains the rule).

@lgalarra : maybe you want to add something ?

I hope this answers your questions,
Cheers,
Jonathan

**Comment by lgalarra** [comment]
Hi,

In general the files in the eval/ directory do not define an integrated library but a set of individual tools for the evaluation of rules in knowledge bases.

Cheers,
Luis

**Comment by falcaopetri** [comment]
Hi, @lgalarra.

Considering the following steps from AMIE's experiments, could you elaborate on the highlighted step, i.e., how did you remove the predictions kwnown at training time?

> We run the systems on an older dataset (YAGO2 [16]). 
> We generate all predictions, i.e., the head atoms of the instantiated rules (see Section 3). 
> **We remove all predictions that are in the old KB**. 
> Then we compare the remaining predicted facts to the successor of that dataset (YAGO2s [34])

Another question about the plot `Aggregated Predictions vs Aggregated Precision`. `Aggregated precision` means the *precision of all predictions so far*, or the *average of the precisions of all rules so far*? I suppose it is the first option, but it seems better to confirm this.

Regards,
Antonio.

**Comment by lgalarra** [comment]
Hi Antonio, 

I am sorry for the delay, I hope it is not too late. This question got buried in my large pile of emails.

**We remove all predictions that are in the old KB**

This means that we only kept those predictions that are not positive examples of the rules. Imagine this is the old KB:
<Diana> <livesIn> <UK>
<Luis> <livesIn> <Ecuador>
<Luis> <wasBornIn> <Ecuador>
<Peter> <livesIn> <France>
<Peter> <wasBornIn> <Germany>

And the rule is ?a <livesIn> ?b => ?a <wasBornIn> ?b. This rule makes three predictions:
<Diana> <wasBornIn> <UK>
<Luis> <wasBornIn> <Ecuador>
<Peter> <wasBornIn> <France>

We remove the second since it is already in the KB. The goal of the evaluation was to assess AMIE's ability to make new predictions, that is, predictions beyond the training KB.

> Another question about the plot Aggregated Predictions vs Aggregated Precision. Aggregated precision means the precision of all predictions so far, or the average of the precisions of all rules so far? I suppose it is the first option, but it seems better to confirm this.

It is the precision of all predictions so far, put differently, cumulative number of correct predictions divided by cumulative number of predictions.

I hope this helps!

Best,
Luis

**Comment by falcaopetri** [comment]
Thanks for the clarifications, @lgalarra. I had to go back on my pipeline, and only now I came back to deal with evaluation. It was not clear to me in which point of the evaluation scripts the "known" predictions were removed.

I was suspecting that `Evaluator.java` did this (something like outputting `EvalResult.True` + `EvalSource.TrainingSource`). Of course, I got lost when I didn't find such code. 

Now I realized that this occur at `Predictor.java`, right? I thought that a prediction outputted by it would mean _"binds with the body"_, but it actually means: _"binds with the body, **but head does not exist in [training] KB**"_. 

.

**Comment by lgalarra** [comment]
Hi Antonio,

As far as I remember, Predictor will simply bind the rules and output their predictions (based on the training KB), whereas Evaluator takes those predictions + the training and testing KBs and labels the predictions as TrainingSource, TargetSource or Undefined depending on whether they are verified by the training KB, target KB, or by none of them.
