### ISSUE TITLE
Where is amie3.jar and where is the output file

### ISSUE THREAD

**Issue by SRL94** [lajus/amie#64]
I did not find a jar file named amie3.jar. Is amie3.jar the same as amie-dev.jar? Where could I find the output file?

**Comment by lgalarra** [comment]
Hello,

amie-dev.jar is not an executable but a package containing the sources and the compiled classes. If you follow the instructions in the README.md file, the file amie3.jar should be located in the directory bin/. If it is not the case, then there is a problem with the compilation. Please keep us posted!

Best,
Luis

**Comment by SRL94** [comment]
Hello,

Thanks for the reply. I followed the instructions named "Running AMIE". In the first line, you just stated that "Download the jar file, and type: java -jar amie3.jar [TSV file]" but I did not find a file named "amie3.jar". Do I need to do some installation?

Best regards
Sirui

**Comment by lajus** [comment]
Hello,

Indeed, it is a bit misleading. amie3.jar is built by maven when you download the sources and compile them on your machine. If you don't want to compile the source code, you can use the [latest release](https://github.com/lajus/amie/releases/tag/3.0) (but the file is named amie-milestone-intKB.jar instead of amie3.jar in that case).

Note that this release is a bit old and contains some bugs if you want to mine rules with more than 3 atoms. It has been fixed in the latest commits but we have not published a new release yet.

Best,
Jonathan
