### ISSUE TITLE
Input TSV file

### ISSUE THREAD

**Issue by lzzhaha** [lajus/amie#72]
Hi,

I want to use AMIE3 to mine some rules from WikiData. I am now trying to convert a WikiData JSON dump to the TSV format required by  AMIE3. 

I wonder should I put the IDs (e.g., "Q31") or the labels ("Belgium") in the TSV file? For instance, suppose the IDs of "Germany", "Population" are "Q100" an "P200" respectively, for the fact "German's population is 83.13 M", should I put "**Germany DELIM Population DELIM 83.13 M [whitespace/tabulation .] NEWLINE**" in the file or put "**Q100 DELIM P200 DELIM 83.13 M [whitespace/tabulation .] NEWLINE**"?

Thank you very much.

**Comment by lgalarra** [comment]
Hi,

Thank you very much for giving AMIE a try. 

AMIE treats RDF terms as strings, hence both alternatives are fine. That said, keeping the Wikidata ids means that your rules will not be directly human-readable. If legibility is important to you and you plan to use AMIE in its default settings, i.e., rules with no constant arguments in the atoms, a solution could be to leave the subjects and objects as Wikidata ids and only translate the predicates -- Wikidata ids are relatively compact so that means less memory usage. If you plan to mine rules with constant arguments, e.g., lives(x, USA) => speaks(x, English), then you probably want to replace all elements in triples with legible identifiers.

If legibility is not very important I would just keep the Wikidata ids to reduce memory consumption. 

By the way, I would definitely exclude predicates whose objects are literals (e.g., 83.13M) because they rarely encode regularities -- unless you are planning to run some specific rule mining that exploits those values.

Best,
Luis

**Comment by lzzhaha** [comment]
Hi,

You mentioned that you "would definitely exclude predicates whose objects are literals (e.g., 83.13M) because they rarely encode regularities", did you mean the subject and objects can only be entities (e.g., Germany)? In WikiData the relations (called 'Property' in WikiData) can also be subject/object in some triples, should I exclude these kind of triples? 

Thank you very much.

**Comment by lgalarra** [comment]
Hi,

Yes, ideally triples should connect entities.  

Object literals, i.e., strings or numbers, will not help you much because they tend to be unique (e.g., populations, ISBNs, etc) and they do not appear as subjects. However, if any of those assumptions does not hold in your data, then you may gain something by leaving them. For example, if some strings are very common, they could appear in rules with constants (even if strings are not allowed as subjects), e.g., film_country(x, USA) => film_code_lang(x, "EN"). This depends on the type of rules you aim to mine.

Best,
Luis

**Comment by lzzhaha** [comment]
Hi,

Got it. Thank you very much.
